site_url: https://example.com/
site_name: Altice ABC
nav:
  - Home: index.md
  - About: about.md
  - Info: 
    - sobre altice: ./info/new-info.md
    - Specification: ./info/more-info/specification.md
    - location: ./info/more-info/locatio.md
  - Serviços: MNMU_PSCSEC+-+Servicos+-+Servicos+-+Menu+IVR+-+Caracteristicas.md
  #- Knowledge Base:
  #    - 'Start here '
theme:
  name: material
  #custom_dir: overrides
  favicon: /img/alticelabs.png
  language: pt 
  #icon:
  #  logo: /img/alticelabs.png
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.links
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  palette: 
    # Palette toggle for light mode
    - scheme: default~
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  puglins:
    - typeset
    - search
copyright: Copyright &copy; 2023 Altice labs
extra:
  enerator: false
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/alticelabs/
    - icon: fontawesome/brands/facebook
      link: https://www.instagram.com/alticelabs/
    - icon: fontawesome/brands/youtube
      link: https://www.instagram.com/alticelabs/
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
    - name: Portugues
      link: /pt/
      lang: pt